### ISSUE TITLE
BombShelter pollutes callbacks

### ISSUE THREAD

**Issue by randoum** [DarthSim/carrierwave-bombshelter#11]
Greetings,

Discovered this issue after upgrading to the latest version.

I have 2 different uploaders `AttachmentUploader` and `WebsiteUploader`. The first one is supposed to accept any kind of files, the second one accept only images files.
I've included `BombShelter` into `WebsiteUploader` only.

When my code uses `AttachmentUploader`, I got the error:

```
NoMethodError: undefined method `protect_from_image_bomb!' for #<AttachmentUploader:0x007f5ca18e26c8>
```

If I remove the line `include CarrierWave::BombShelter` from `WebsiteUploader`, the error disappear.
I think the [way you implement the callback](https://github.com/DarthSim/carrierwave-bombshelter/blob/master/lib/carrierwave/bombshelter.rb#L20) is faulty.

Sorry I have no time to dive deeper, so I leave it to you as a FYI.

Cheers

**Comment by DarthSim** [comment]
@randoum Thanks for discovery! Fixed.
